name: jsonrpc2
author: Jim Washington <washington.jim@gmail.com>
version: 0.8.9
description: JSON-RPC utilities for web applications.
dependencies:
  logging: '>=0.9.0 <0.9.1'
  logging_handlers: '>=0.8.0 <0.8.1'
dev_dependencies:
  polymer: any
  start: 0.1.1
  unittest: any
