name: jsonrpc2flutter
version: 1.0.0
author: Billy Lam <billylam.nz@gmail.com>
description: Repackaged version of jsonrpc2-dart for flutter. Compatible with dart 2.0.
homepage: https://github.com/Intelx/jsonrpc2-flutter
environment:
  sdk: '>=2.0.0 <3.0.0'

