name: jsonrpc2
author: Jim Washington <washington.jim@gmail.com>
version: 0.9.0
homepage: https://github.com/jwashin/jsonrpc2-dart
description: JSON-RPC utilities for web applications.
dependencies:
  logging: any
  logging_handlers: '>=0.8.0 <0.8.1'
dev_dependencies:
  start: 0.2.0
  unittest: any
