name: jsonrpc2
author: Jim Washington
version: 0.8.9
description: JSON-RPC utilities for web applications.
dependencies:
  logging: any
  logging_handlers: any
dev_dependencies:
  polymer: any
  start: 0.1.1
  unittest: any
