name: jsonrpc2
version: 0.9.0
author: Jim Washington <washington.jim@gmail.com>
description: JSON-RPC utilities for web applications.
homepage: https://github.com/jwashin/jsonrpc2-dart
dependencies:
  browser: any
  logging: any
  logging_handlers: '>=0.8.0 <0.8.1'
dev_dependencies:
  start: 0.2.0
  unittest: any
