name: rpc_example
description: A sample Polymer application
dependencies:
  jsonrpc2: any
  logging: any
  logging_handlers: any
  start: 0.2.0
transformers:
- polymer:
    entry_points: web/testrpc.html
